Ncnews 6
H-Shihaibi/HS-NC-News pull request #5
Opened 2022-09-07 01:22 UTC by H-Shihaibi

code review nc news tickets 5-6 - mistakenly didn't add 5 previously

2022-09-07 09:00 UTC, HMelesi requested changes
Task 5: GET /api/users - all approved, well done Hamam :) 

Task 6: PATCH /api/articles/:article_id - quite a few changes requested on this one, have a look at my comments and let me know if anything is unclear.

2022-09-07 20:42 UTC, H-Shihaibi commented on __tests__/app.test.js
> +        expect().toBe();
Deleted, thanks!

2022-09-07 20:43 UTC, H-Shihaibi commented on __tests__/app.test.js
> +      });
Done!

2022-09-07 20:43 UTC, H-Shihaibi commented on __tests__/app.test.js
> +      votes: +1,
Removed.

2022-09-07 20:43 UTC, H-Shihaibi commented on __tests__/app.test.js
> +      votes: +1,
Removed

2022-09-07 20:59 UTC, H-Shihaibi commented on __tests__/app.test.js
> +          ...body.article,
Good shout! I've added an object const to the test and replaced the (...body.article).

2022-09-07 21:23 UTC, H-Shihaibi commented on __tests__/app.test.js
> +          ...body.article,
Done

2022-09-07 21:24 UTC, H-Shihaibi commented on __tests__/app.test.js
> +        expect(body.article.votes).toBe(1);
Noted

2022-09-07 21:30 UTC, H-Shihaibi commented on controllers/articles-controller.js
> +  const input = req.params.article_id;
Done

2022-09-07 21:31 UTC, H-Shihaibi commented on controllers/articles-controller.js
> +  const newVotesCount = req.body;
Good note - All done, to fail and work.

2022-09-07 21:31 UTC, H-Shihaibi commented on models/articles.model.js
> +  const { votes } = newVotesCount;
done

2022-09-07 21:31 UTC, H-Shihaibi commented on models/articles.model.js
> +  const arrValues = [votes, articleId];
Thanks!

2022-09-08 10:22 UTC, HMelesi approved these changes

2022-09-08 11:20 UTC, merged